layout_spectrum: 0.16498653943004954
typography_spectrum: 0.523775185914618
color:
  brandStrength: 0.6993707162886857
  lightness: 0.4863746038174238
  saturation: 0.4434031924528835
  rhythmicContrast: 0.2828298866755265
  brandColors:
    - '#DC3522'
    - '#D9CB9E'
    - '#374140'
    - '#2A2C2B'
    - '#1E1E20'
content_rating:
  adult: false
github: true
analytics:
  facebook: '786094331529434'
  google: UA-87730697-1
author:
  name: Spencer Harber
  email: spencer_harber@yahoo.com
  url: spencerforhigher.com
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/b3ad83c4-6e08-417b-8978-8d321c7e6fcd.png
name: Spencer for Higher
url: 'https://spencerforhigher.com'
navigation:
  - name: About
    id: e3240098-4c63-45b7-a76f-e4d93eeb5457
    type: content
  - name: Nutrition
    url: 'http://nutritionstudies.org/slides/grad-presentation/#/'
    type: external
  - name: Instagram
    url: 'https://www.instagram.com/spencer.for.higher/'
    type: external
  - name: Facebook
    url: 'https://www.facebook.com/spencerforhigher1/'
    type: external
  - name: YouTube
    url: 'https://www.youtube.com/channel/UCX0kAtWT2sPwcdqmnPpfLbA'
    type: external
  - name: Blog
    url: 'http://blog.spencerforhigher.com/'
    type: external
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/d3a80009-9759-476f-9b68-3520e80c8025.png
title: Spencer for Higher LLC
content: []
description: Discover Your Higher Ability
purpose:
  - type: contact
    url: 'mailto:spencerforhigher1@gmail.com'
    label: Contact me
  - type: external
    url: 'https://spencerforhigher.acuityscheduling.com/'
    label: Schedule your Appointment!
