typography_spectrum: 0.981050587211007
content_rating:
  adult: false
color:
  brandStrength: 0.076414893751798
  lightness: 0.2195307867775791
  saturation: 0.5995509593236712
  rhythmicContrast: 0.003356062463659904
  brandColors:
    - '#225378'
    - '#1695A3'
    - '#ACF0F2'
    - '#F3FFE2'
    - '#EB7F00'
github: true
layout_spectrum: 0.9591596005627387
analytics:
  facebook: '786094331529434'
  google: UA-87730697-1
author:
  name: Spencer Harber
  email: spencer_harber@yahoo.com
  url: spencerforhigher.com
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/b3ad83c4-6e08-417b-8978-8d321c7e6fcd.png
name: Spencer for Higher
navigation:
  - name: About
    id: e3240098-4c63-45b7-a76f-e4d93eeb5457
    type: content
  - name: Blog
    id: eb9b8b60-b646-4fd0-a94f-464b5ebdfb65
    type: content
  - name: Instagram
    url: 'https://www.instagram.com/spencer.for.higher/'
    type: external
  - name: Facebook
    url: 'https://www.facebook.com/spencerforhigher1/'
    type: external
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/d3a80009-9759-476f-9b68-3520e80c8025.png
title: Wellness Investigator
content: []
description: Discover Your Higher Ability
purpose:
  - type: contact
    url: 'mailto:spencerforhigher1@gmail.com'
    label: Inquire
  - type: external
    url: >-
      https://docs.google.com/forms/d/e/1FAIpQLSd-RapfHp8vAt84vpZ-92BobR4m-zBpVKcMsdBmXa02h4Yyzw/viewform
    label: Free Yoga Sign Up!
