typography_spectrum: 0.33116585022631556
content_rating:
  adult: false
color:
  brandStrength: 0.8796973813770542
  lightness: 0.35552598072335784
  saturation: 1
  rhythmicContrast: 0.13255444721724507
  brandColors:
    - '#225378'
    - '#1695A3'
    - '#ACF0F2'
    - '#F3FFE2'
    - '#EB7F00'
github: true
layout_spectrum: 0.28103582013721146
analytics:
  facebook: '786094331529434'
  google: UA-87730697-1
author:
  name: Spencer Harber
  email: spencer_harber@yahoo.com
  url: spencerforhigher.com
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/b3ad83c4-6e08-417b-8978-8d321c7e6fcd.png
name: Spencer for Higher
url: 'https://spencerforhigher.com'
navigation:
  - name: About
    id: e3240098-4c63-45b7-a76f-e4d93eeb5457
    type: content
  - name: Nutrition
    url: 'http://nutritionstudies.org/slides/grad-presentation/#/'
    type: external
  - name: Instagram
    url: 'https://www.instagram.com/spencer.for.higher/'
    type: external
  - name: Facebook
    url: 'https://www.facebook.com/spencerforhigher1/'
    type: external
  - name: YouTube
    url: 'https://www.youtube.com/channel/UCX0kAtWT2sPwcdqmnPpfLbA'
    type: external
  - name: Blog
    url: 'http://blog.spencerforhigher.com/'
    type: external
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/d3a80009-9759-476f-9b68-3520e80c8025.png
title: Wellness Investigator
content:
  - id: !<tag:yaml.org,2002:js/undefined> ''
    type: video
    html: >-
      <iframe
      src="https://cdn.embedly.com/widgets/media.html?src=https%3A%2F%2Fwww.youtube.com%2Fembed%2F7OeyJVG4x0E%3Ffeature%3Doembed&url=http%3A%2F%2Fwww.youtube.com%2Fwatch%3Fv%3D7OeyJVG4x0E&image=https%3A%2F%2Fi.ytimg.com%2Fvi%2F7OeyJVG4x0E%2Fhqdefault.jpg&key=b7d04c9b404c499eba89ee7072e1c4f7&type=text%2Fhtml&schema=youtube"
      width="640" height="360" scrolling="no" frameborder="0"
      allowfullscreen></iframe>
    src: !<tag:yaml.org,2002:js/undefined> ''
    metadata:
      author:
        - name: Spencer for Higher
          url: 'https://www.youtube.com/channel/UCX0kAtWT2sPwcdqmnPpfLbA'
          avatar: {}
      related: []
      publisher:
        url: 'https://www.youtube.com/'
        name: YouTube
        favicon: 'https://s.ytimg.com/yts/img/favicon-vflz7uhzw.ico'
        domain: youtu.be
      keywords:
        - youtube
        - comedy
        - spencer
        - higher
        - spencer for higher
        - yoga
        - yoga for kids
        - girls yoga
        - kids yoga
        - grace
        - ava
        - ego
        - ego check
        - wellness
        - showoff
        - muscle flex
      description: >-
        We found this gem when looking through some yoga footage we shot for
        another project! In this short clip, Grace discovers that she has fallen
        in love with flexing her strong muscles, Ava catches her, and hilarity
        ensues. "Check yourself" today!
      inLanguage: !<tag:yaml.org,2002:js/undefined> ''
      '@type': VideoObject
      app_links:
        - url: 'vnd.youtube://www.youtube.com/watch?v=7OeyJVG4x0E&feature=applinks'
          type: ios
          namespace: ai
          app_store_id: '544007664'
          app_name: YouTube
        - url: 'vnd.youtube://www.youtube.com/watch?v=7OeyJVG4x0E&feature=applinks'
          type: android
          namespace: ai
          app_name: YouTube
          package: com.google.android.youtube
        - url: 'https://www.youtube.com/watch?v=7OeyJVG4x0E&feature=applinks'
          type: web
          namespace: ai
        - url: 'vnd.youtube://www.youtube.com/watch?v=7OeyJVG4x0E&feature=applinks'
          namespace: twitter
          type: ipad
          name: YouTube
          id: '544007664'
        - url: 'vnd.youtube://www.youtube.com/watch?v=7OeyJVG4x0E&feature=applinks'
          namespace: twitter
          type: iphone
          name: YouTube
          id: '544007664'
        - url: 'https://www.youtube.com/watch?v=7OeyJVG4x0E'
          namespace: twitter
          type: googleplay
          name: YouTube
          id: com.google.android.youtube
        - path: http/www.youtube.com/watch?v=7OeyJVG4x0E
          package: com.google.android.youtube
          namespace: google
          type: android
        - path: vnd.youtube/www.youtube.com/watch?v=7OeyJVG4x0E
          package: '544007664'
          namespace: google
          type: ios
      '@context': 'http://schema.org'
      isBasedOnUrl: 'https://youtu.be/7OeyJVG4x0E'
      title: Ava ego checks Grace
      datePublished: null
    title: !<tag:yaml.org,2002:js/undefined> ''
    caption: !<tag:yaml.org,2002:js/undefined> ''
    text: !<tag:yaml.org,2002:js/undefined> ''
description: Discover Your Higher Ability
purpose:
  - type: contact
    url: 'mailto:spencerforhigher1@gmail.com'
    label: Contact me
  - type: external
    url: 'https://spencerforhigher.acuityscheduling.com/'
    label: Schedule your Appointment!
