layout_spectrum: 0.16498653943004954
typography_spectrum: 0.523775185914618
color:
  brandStrength: 0.6993707162886857
  lightness: 0.4863746038174238
  saturation: 0.4434031924528835
  rhythmicContrast: 0.2828298866755265
  brandColors:
    - '#DC3522'
    - '#D9CB9E'
    - '#374140'
    - '#2A2C2B'
    - '#1E1E20'
content_rating:
  adult: false
github: true
analytics:
  facebook: '786094331529434'
  google: UA-87730697-1
author:
  name: Spencer Harber
  email: spencer_harber@yahoo.com
  url: spencerforhigher.com
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/b3ad83c4-6e08-417b-8978-8d321c7e6fcd.png
name: Spencer for Higher
url: 'https://spencerforhigher.com'
navigation:
  - name: About
    id: e3240098-4c63-45b7-a76f-e4d93eeb5457
    type: content
  - name: Nutrition
    url: 'http://nutritionstudies.org/slides/grad-presentation/#/'
    type: external
  - name: Instagram
    url: 'https://www.instagram.com/spencer.for.higher/'
    type: external
  - name: Facebook
    url: 'https://www.facebook.com/spencerforhigher1/'
    type: external
  - name: YouTube
    url: 'https://www.youtube.com/channel/UCX0kAtWT2sPwcdqmnPpfLbA'
    type: external
  - name: Blog
    url: 'http://blog.spencerforhigher.com/'
    type: external
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/d3a80009-9759-476f-9b68-3520e80c8025.png
title: Spencer for Higher
content:
  - id: !<tag:yaml.org,2002:js/undefined> ''
    type: video
    html: >-
      <iframe
      src="https://cdn.embedly.com/widgets/media.html?src=https%3A%2F%2Fwww.youtube.com%2Fembed%2Ftv9CShrX4Ys%3Ffeature%3Doembed&url=http%3A%2F%2Fwww.youtube.com%2Fwatch%3Fv%3Dtv9CShrX4Ys&image=https%3A%2F%2Fi.ytimg.com%2Fvi%2Ftv9CShrX4Ys%2Fhqdefault.jpg&key=a715cf41cc93453ca338d350cd26f87b&type=text%2Fhtml&schema=youtube"
      width="640" height="360" scrolling="no" frameborder="0"
      allowfullscreen></iframe>
    src: !<tag:yaml.org,2002:js/undefined> ''
    metadata:
      author:
        - name: Spencer for Higher
          url: 'https://www.youtube.com/channel/UCX0kAtWT2sPwcdqmnPpfLbA'
          avatar: {}
      related: []
      publisher:
        url: 'https://www.youtube.com/'
        name: YouTube
        favicon: 'https://s.ytimg.com/yts/img/favicon-vfl8qSV2F.ico'
        domain: www.youtube.com
      keywords:
        - spencer
        - higher
        - spencer for higher
        - wellness
        - yoga
        - health
        - plant based cooking
        - vegan
        - children
        - humor
        - wellness coach
        - master
        - art
        - higher ability
        - yoga f...
      description: >-
        Hello and welcome to Spencer for Higher's YouTube channel! You will find
        everything health and wellness right here! We are pleased to bring you
        humorous tips on wellness, yoga, plant-based cooking, massage, intimacy,
        relationships, and anything else that supports your journey towards your
        higher self!
      '@type': VideoObject
      app_links:
        - url: 'vnd.youtube://www.youtube.com/watch?v=tv9CShrX4Ys&feature=applinks'
          type: ios
          namespace: ai
          app_store_id: '544007664'
          app_name: YouTube
        - url: 'vnd.youtube://www.youtube.com/watch?v=tv9CShrX4Ys&feature=applinks'
          type: android
          namespace: ai
          app_name: YouTube
          package: com.google.android.youtube
        - url: 'https://www.youtube.com/watch?v=tv9CShrX4Ys&feature=applinks'
          type: web
          namespace: ai
        - url: 'vnd.youtube://www.youtube.com/watch?v=tv9CShrX4Ys&feature=applinks'
          namespace: twitter
          type: ipad
          name: YouTube
          id: '544007664'
        - url: 'vnd.youtube://www.youtube.com/watch?v=tv9CShrX4Ys&feature=applinks'
          namespace: twitter
          type: iphone
          name: YouTube
          id: '544007664'
        - url: 'https://www.youtube.com/watch?v=tv9CShrX4Ys'
          namespace: twitter
          type: googleplay
          name: YouTube
          id: com.google.android.youtube
        - path: http/www.youtube.com/watch?v=tv9CShrX4Ys
          package: com.google.android.youtube
          namespace: google
          type: android
        - path: vnd.youtube/www.youtube.com/watch?v=tv9CShrX4Ys
          package: '544007664'
          namespace: google
          type: ios
      '@context': 'http://schema.org'
      isBasedOnUrl: 'https://www.youtube.com/watch?v=tv9CShrX4Ys'
      title: Spencer for Higher - YouTube Introduction
      datePublished: null
    title: !<tag:yaml.org,2002:js/undefined> ''
    caption: !<tag:yaml.org,2002:js/undefined> ''
    text: !<tag:yaml.org,2002:js/undefined> ''
description: Discover Your Higher Ability
purpose:
  - type: contact
    url: 'mailto:spencerforhigher1@gmail.com'
    label: Contact me
  - type: external
    url: 'https://spencerforhigher.acuityscheduling.com/'
    label: Schedule your Appointment!
