layout_spectrum: 0.9591596005627387
typography_spectrum: 0.981050587211007
color:
  brandStrength: 0.076414893751798
  lightness: 0.2195307867775791
  saturation: 0.5995509593236712
  rhythmicContrast: 0.003356062463659904
  brandColors:
    - '#225378'
    - '#1695A3'
    - '#ACF0F2'
    - '#F3FFE2'
    - '#EB7F00'
content_rating:
  adult: false
github: true
author:
  name: Spencer Harber
  email: spencer_harber@yahoo.com
  url: spencerforhigher.com
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/aa15a2e0-3000-416b-9a4e-df001e41fccc.jpg
name: Spencer for Higher
navigation:
  - name: About
    id: e3240098-4c63-45b7-a76f-e4d93eeb5457
    type: content
  - name: Blog
    id: eb9b8b60-b646-4fd0-a94f-464b5ebdfb65
    type: content
title: Wellness Investigator
content: []
description: Discover Your Higher Ability
purpose:
  - type: contact
    url: 'mailto:spencerforhigher1@gmail.com'
    label: Inquire
  - type: external
    url: >-
      https://docs.google.com/forms/d/e/1FAIpQLSd-RapfHp8vAt84vpZ-92BobR4m-zBpVKcMsdBmXa02h4Yyzw/viewform
    label: Free Yoga Sign Up!
