typography_spectrum: 0.33116585022631556
content_rating:
  adult: false
color:
  brandStrength: 0.8796973813770542
  lightness: 0.35552598072335784
  saturation: 1
  rhythmicContrast: 0.13255444721724507
  brandColors:
    - '#225378'
    - '#1695A3'
    - '#ACF0F2'
    - '#F3FFE2'
    - '#EB7F00'
github: true
layout_spectrum: 0.28103582013721146
analytics:
  facebook: '786094331529434'
  google: UA-87730697-1
author:
  name: Spencer Harber
  email: spencer_harber@yahoo.com
  url: spencerforhigher.com
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/b3ad83c4-6e08-417b-8978-8d321c7e6fcd.png
name: Spencer for Higher
url: 'https://spencerforhigher.com'
navigation:
  - name: About
    id: e3240098-4c63-45b7-a76f-e4d93eeb5457
    type: content
  - name: Instagram
    url: 'https://www.instagram.com/spencer.for.higher/'
    type: external
  - name: Facebook
    url: 'https://www.facebook.com/spencerforhigher1/'
    type: external
  - name: Blog
    url: 'http://blog.spencerforhigher.com/'
    type: external
  - name: Nutrition
    url: 'http://nutritionstudies.org/slides/grad-presentation/#/'
    type: external
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/d3a80009-9759-476f-9b68-3520e80c8025.png
title: Wellness Investigator
content:
  - id: !<tag:yaml.org,2002:js/undefined> ''
    type: video
    html: >-
      <iframe
      src="https://cdn.embedly.com/widgets/media.html?src=https%3A%2F%2Fwww.youtube.com%2Fembed%2FtAf3i__fT2U%3Ffeature%3Doembed&url=http%3A%2F%2Fwww.youtube.com%2Fwatch%3Fv%3DtAf3i__fT2U&image=https%3A%2F%2Fi.ytimg.com%2Fvi%2FtAf3i__fT2U%2Fhqdefault.jpg&key=b7d04c9b404c499eba89ee7072e1c4f7&type=text%2Fhtml&schema=youtube"
      width="640" height="360" scrolling="no" frameborder="0"
      allowfullscreen></iframe>
    src: !<tag:yaml.org,2002:js/undefined> ''
    metadata:
      datePublished: null
      isBasedOnUrl: 'https://www.youtube.com/watch?v=tAf3i__fT2U'
      keywords:
        - duration
        - views
        - song
        - spencerforhigher
        - rhett
        - '879'
        - '704'
        - jackman
        - duets
        - lady
      related: []
      author:
        - name: Spencer for Higher
          url: 'https://www.youtube.com/channel/UCX0kAtWT2sPwcdqmnPpfLbA'
          avatar: {}
      '@context': 'http://schema.org'
      title: I'm Done!
      '@type': VideoObject
      app_links:
        - url: 'vnd.youtube://www.youtube.com/watch?v=tAf3i__fT2U&feature=applinks'
          type: ios
          namespace: ai
          app_store_id: '544007664'
          app_name: YouTube
        - url: 'vnd.youtube://www.youtube.com/watch?v=tAf3i__fT2U&feature=applinks'
          type: android
          namespace: ai
          app_name: YouTube
          package: com.google.android.youtube
        - url: 'https://www.youtube.com/watch?v=tAf3i__fT2U&feature=applinks'
          type: web
          namespace: ai
        - url: 'vnd.youtube://www.youtube.com/watch?v=tAf3i__fT2U&feature=applinks'
          namespace: twitter
          type: ipad
          name: YouTube
          id: '544007664'
        - url: 'vnd.youtube://www.youtube.com/watch?v=tAf3i__fT2U&feature=applinks'
          namespace: twitter
          type: iphone
          name: YouTube
          id: '544007664'
        - url: 'https://www.youtube.com/watch?v=tAf3i__fT2U'
          namespace: twitter
          type: googleplay
          name: YouTube
          id: com.google.android.youtube
        - path: http/www.youtube.com/watch?v=tAf3i__fT2U
          package: com.google.android.youtube
          namespace: google
          type: android
        - path: vnd.youtube/www.youtube.com/watch?v=tAf3i__fT2U
          package: '544007664'
          namespace: google
          type: ios
      publisher:
        url: 'https://www.youtube.com/'
        name: YouTube
        favicon: 'https://s.ytimg.com/yts/img/favicon-vflz7uhzw.ico'
        domain: www.youtube.com
      description: >-
        My exact feelings after completing my Master's degree in Health &
        Wellness coaching. A Spencer for Higher Short. Please visit
        http://spencerforhigher.com/ or http://blog.spencerforhigher.com/ for
        more humorous inspiration!
      inLanguage: en
    title: !<tag:yaml.org,2002:js/undefined> ''
    caption: !<tag:yaml.org,2002:js/undefined> ''
    text: !<tag:yaml.org,2002:js/undefined> ''
description: Discover Your Higher Ability
purpose:
  - type: contact
    url: 'mailto:spencerforhigher1@gmail.com'
    label: Contact me
  - type: external
    url: 'https://spencerforhigher.acuityscheduling.com/'
    label: Schedule your Appointment!
